Repository Power-Rangers-ALM-Force/Test-Repository-Index-01, pull requests merged in 2020-04, with the labels that each got.

#2 Update README
  README.md
Labels: bug

#14 Getheight fix
  src/main/java/Main.java
Labels: hotfix

#15 Getheight fixs
  src/main/java/Main.java
Labels: hotfix

#17 test
  src/main/java/Person.java
  src/test/java/PersonTest.java
Labels: feature

#19 test
  src/main/java/Person.java
  src/test/java/PersonTest.java
Labels: feature
